BIDS-numpy/npreadtext

.github/workflows/tests.yml, compat/check_loadtxt_compat.py
The two main changes are:
1. Updates Python/numpy versions in testing matrix
2. Adds more stringent np.loadtxt compatibility tests
This PR also reorganizes the test suite so that macos and windows jobs can be added easily, though #3 and #4 should be fixed before these jobs are added.
Re: point 2 - Previously, the CI ran the np.loadtxt test suite in a job that was allowed to fail because there are some tests that fail (8 at current count) that `npreadtext._loadtxt` is not yet fuly compatible with `np.loadtxt`. The problem with this is that if other compat tests that had previously been passing failed because of new changes, it would be difficult to catch this in CI.
I've refactored the compatibility tests so that there are two separate jobs running. The first includes all the compatibility …
=> Update tests in CI

src/analyze.c, src/analyze.h, src/char32utils.c, src/conversions.c, src/conversions.h, src/field_types.c, src/field_types.h, src/max_token_len.c, src/max_token_len.h, src/parser_config.c, src/parser_config.h, src/rows.c, src/rows.h, src/str_to.c, src/str_to.h, src/str_to_double.c, src/str_to_int.c, src/stream_file.c, src/stream_file.h, src/stream_python_file_by_line.c, src/stream_python_file_by_line.h, src/tokenize.c, src/tokenize.h, src/type_inference.c, src/type_inference.h
I prefer this style, it also makes finding function names easier.
The other changes, are "seberg" style maybe, and I don't care much.
(this is just because if I don't do it, I am tempted to change it
when close to the code anyway.)
=> STY: Ensure all C-function definitions start with the name

.github/workflows/tests.yml, npreadtext/_readers.py
Replaces the one instance of `_readtext_from_filename` by instead using `np.lib._datasource.open` to handle the file opening and passing in the result to `_readtext_from_file_object` instead. This has the immediate benefit of fixing the `test_universal_newline` compatibility test, but more generally I think it simplifies the handling of encoding and e.g. compressed files.
I think this is also related to #9. I'm not sure yet, but it may be possible to remove the low-level `filename` utilities (e.g. `stream_from_filename, `_readtext_from_filename` from `npreadtext` entirely. Assuming there are no severe performance penalties, I think this may be preferable as it will make compatibility easier not only with `np.loadtxt` but with Python file handling in general, and can help avoid thorny …
=> Handle encoding in python layer

.github/workflows/tests.yml, src/_readtextmodule.c, src/field_types.c, src/rows.c, src/stream.h
Mostly a few small compiler warnings fixes.  There are still some left, mainly about comparing signed and unsigned ints (for things like num-rows).  I also have a `use_blocks` uninitialized warnings in `rows.c` (and one more), those seems probably spurious.
=> MAINT: Fix some compiler warnings (or add comments on hard to fix)

src/_readtextmodule.c
Just because my static analyzer keeps bugging me about it really.
If you want to add a test for this: The broken path would be passing
in an empty comment, because it would read a byte too many.
There are more issues here: These are all `char` and not unicode
as they should be...  Apparently, there are probably no tests that
use unicode separators, even though the code should handle them just
fine.
=> BUG: Fix comment ternary operator

src/_readtextmodule.c, src/stream_file.c, src/stream_file.h
I am not sure this is ideal, but I think the proper solution needs
to rearrange things a bit more in any case.\
---
I tried a `%timeit` on an actual file, and the program ran out of file descriptors or so :) (It could not open more), confused IPython a lot ;).
=> BUG: Closes file by removing `stream_file_from_filename`

.github/workflows/tests.yml, npreadtext/_readers.py, setup.py, src/_readtextmodule.c, src/analyze.c, src/blocks.c, src/blocks.h, src/field_types.c, src/field_types.h, src/rows.c, src/rows.h, src/str_to_int.c, src/str_to_int.h, src/type_inference.c, src/type_inference.h
This also reorganizes a bit, and I just deleted the currently
unused `from_filename`, that seemed easier, since otherwise it
just means updating duplicated things.
I modified the type structure to rely on itemsize rather than codes.
That currently breaks some errors (because it has the incorrect
types for the fields).
In the current stage it may still crash down in flames, but it is
a start, and probably fairly far along.
---
Also invalidates a number of C-level tests probably, I did not bother about that.  And some stuff needs cleaning up: but I consider npreadtext in pretty high flux mode still, so...
=> ENH: Rework numpy dtypes into everything

npreadtext/_readers.py, npreadtext/tests/test_read.py, src/_readtextmodule.c, src/rows.c, src/rows.h
While working with arrays in the row reader is a bit annoying in
parts (because why?).  It also is somewhat necessary unfortunately.
This solves the problem that having the array already ready
greatly simplifies cleanup when the result has an object dtype.
(It also is a bit nicer for growing the strings, since we can just
use the NumPy API to copy.)
I don't think this is really much nicer and if NumPy grows better
API to decref a chunk of memory content, rather than relying on
having the array object around it would be worse probably...
But this is what we got currently, mutating/creating the array
object inside `read_rows` just seems more practical
=> MAINT,BUG: Work arrays into the core of rows

src/analyze.c, src/type_inference.c
As far as I understand this was necessary for datetime support.
We don't support datetime (explicitly), so don't worry about it for
now.
Another reason to remove the macro, is that I am also not sure how
portable it actually is.
=> MAINT: Remove XOPEN_SOURCE definition from C files

src/rows.h
This should have been removed in the PR that restructured the
parsing error reporting.
=> MAINT: Delete unused error reporting helper struct

setup.py
This is necessary (I think) to make the package installable via pip from somewhere other than the source directory.
=> Add header files to extension include_dir.

npreadtext/_readers.py, npreadtext/tests/test_read.py, src/_readtextmodule.c, src/stream_pyobject.c
In particular, just use the `char *` in C directly, that seems easier.
This does not figure out whether the encoding we currently use is
actually the *right* encoding.
(I am also not 100% sure if encoding names can include unicode characters
and if utf-8 encoding of the encoding is right then :).  But I would be
extremely surprised if this is not right and even more if it mattered.)
=> MAINT: Clean up encoding handling slightly

npreadtext/_readers.py, npreadtext/tests/test_read.py, src/conversions.c, src/stream_pyobject.c, src/stream_pyobject.h
We assume that "casting" to bytes/S dtype is OK so long we are
in the latin1 range (which is compatible to unicode).
Otherwise, we just fail.
I left a TODO in the code, raising the generic `ValueError`, may not be best here.  (And it used to be a UnicodeDecodeError.)
---
The PR includes a few cleanups/maintanence fixes.
=> BUG: Correctly check for out-of-bound unicode characters

.github/workflows/tests.yml, npreadtext/_readers.py, npreadtext/tests/test_read.py, src/_readtextmodule.c, src/conversions.c, src/parser_config.h
Adds support for byte-converters and reorganizes the file opening to match the current loadtxt file opening strategy much more closely.
This is based on gh-7 and supersedes it.  It does not include the changes to the string size detection.  That is because right now I tend towards the "python solution" see gh-76
=> BUG: loadtxt compatibility: handle byte converters

npreadtext/tests/test_read.py, src/rows.c
This chains the exception for now, something that I thought might be nice, but initially did not do when I worked on it:
This leads (for example) to the following as of now:
```python
In [5]: read(["asdf", "fdsa"], dtype="int", converters={0: int})
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
ValueError: invalid literal for int() with base 10: 'asdf'
The above exception was the direct cause of the following exception:
ValueError                                Traceback (most recent call last)
<ipython-input-5-f78ed236dfab> in <module>
----> 1 read(["asdf", "fdsa"], dtype="int", converters={0: int})
~/forks/npreadtext/npreadtext/_readers.py in read(file, delimiter, comment, quote, …
```
=> ENH: Chain exceptions if parsing a field failed.

.github/workflows/tests.yml, npreadtext/_readers.py, src/_readtextmodule.c, src/conversions.c, src/parser_config.h, src/rows.c
This will fix the dtype discovery for datetimes and with converters.
It of course also should significantly slow things down if the
string size needs to be discovered.
---
Marking as draft, I will have to rebase it on the byte-converter stuff.  In particular, the byte-converter flag will be helpful/necessary here to ensure we put byte-strings into the object array when the final result is of "S" dtype.
This probably needs a bit more refactor and it does move some paths back into Python for simplicity...
EDIT: Would address gh-74 and gh-34
=> BUG,MAINT: Move dtype "discovery" to python (including string size)

npreadtext/_readers.py, npreadtext/tests/test_read.py, src/rows.c
This attempts to align converter logic to be as it is right now
for loadtxt (as imperfect that is).  The only thing we don't do
the same way is that:
1. Non-integer converters don't get ignored when usecols are used
2. We don't support duck-typed `obj.items()` but enforce a dict.
=> BUG: Fix converters to work like loadtxt

npreadtext/__init__.py, npreadtext/_loadtxt.py, npreadtext/_readers.py, npreadtext/monkeypatch_numpy.py, src/conversions.c
This allows:
```
from npreadtext import monkeypatch_numpy
```
printing out a warning and then replacing `loadtxt` in NumPy with our version.  It also does some smaller fixups first (and two small bug-fixes, grrr).
=> ENH: Introduce from npreadtext import monkeypatch_numpy

src/dtoa_modified.c, src/str_to.h
We could discuss rolling some of this back, but Python allows any
whitespace in numbers (e.g. even newlines if this is a quoted field).
This will probably slow parsing down an inkling, so if we want we
may be able to recover some of that.
But for now, it seems like the correct/safe thing to do.
=> BUG: Catch all unicode "whitespaces" when parsing numbers

src/tokenize.c.src
I just had it wrong in most places, but since all that typically
happens would be inserting a blank line, it is hard to notice.
I had a fix already, but that actually made it possible to modify
the newline (and carriage) character (useful for `linterminator`
support other than universal-newline, also potentially useful to
ignore newline characters when the user passes a list of strings).
In any case, since we don't need that right now, this just swaps
fixes the logic for now.
=> BUG: Swap `\n` and `\r` in the `\r\n` support

README.rst
Trying to do a better job of documenting some of these nuggets. We should probably collate things like this in a more formal document somewhere/someday, but adding to the README for now. Adds a couple relevant links for further info.
=> Add note about pandas float parsing to README

npreadtext/tests/test_read.py, src/conversions.c, src/conversions.h, src/field_types.c
Bools currently work via integers.  It may make sense to change
that or limit it, but probably not in the first step.
Closes gh-67
=> BUG: Implement boolean conversion largly equivalent to loadtxt

src/conversions.c, src/conversions.h
Also simplifies the double code: Since it is fortified against
stray NUL characters, there is no need to check whether the string
is empty up-front.
This further fixes leading (and trailing non-space) whitespaces
which come before or after the the parentheses of the complex
number.
---
Fixes gh-42 although does not add tests.
=> BUG: Fixup stray NUL characters in complex

npreadtext/_readers.py, npreadtext/tests/test_read.py, src/_readtextmodule.c, src/field_types.c, src/field_types.h, src/parser_config.h, src/rows.c, src/rows.h, src/tokenize.h
This fixes the offset handling into structured dtypes by moving
the dtype flattening code to C.
By doing that, it also fixes gh-75 and gh-94.
At the time adds a (harmless) compiler warning which should be
removed, but I may just put this in without fixing it.
=> BUG: Move struct-dtype flattening to C and fix offsets
